name: Release

on:
  workflow_dispatch:
    inputs:
      version_scale:
        type: choice
        description: Release Scale
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.THUNDRA_GITHUB_ACCESS_TOKEN }}
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: https://registry.npmjs.org

      - name: NPM Install for Lambda
        run: npm install -f ./lambdas --prefix ./lambdas

      - name: NPM Install
        run: npm install

      - name: NPM Publish
        run: npm run relaese
        env:
          VERSION_SCALE: ${{ github.event.inputs.version_scale }}
          NODE_AUTH_TOKEN: ${{ secrets.THUNDRA_NPM_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.THUNDRA_GITHUB_ACCESS_TOKEN }}
